### ISSUE TITLE
Fail to Installation

### ISSUE THREAD

**Issue by Bwformer** [NVlabs/earth2grid#14]
Hi,
I tried to install _earth2grid_ following the instructions. But it fails as follows:

![image](https://github.com/user-attachments/assets/10cda5d6-fe08-43db-8059-a9537cfbdf30)

Do you have any idea what's going on?

**Comment by nbren12** [comment]
Hi. It's hard to tell. What version of python/pip are you using?

**Comment by Bwformer** [comment]
I try to install it with the following environment:
python=3.10.4
pip=22.1.2
And I updated the pip to the latest version (pip-24.2), but it failed again.
Do you have any comments about the required environment?
Thanks.

**Comment by nbren12** [comment]
huh. I've run on python=3.10 (and probably lower).

Looking at your error, I think it is not interpreting the string `earth2grid` as a file path but as a package name instead. It fails to find anything named `earth2grid` in the public repositories.

To fix, please run
```
pip install --no-build-isolation ./earth2grid
```
The "./" will force pip to interpret the argument as a path. 

I'll fix the typo in the docs.

**Comment by nbren12** [comment]
Resolved by c493e48e2dffdde4162e6af0ad67f84527616795
